### ISSUE TITLE
[Feature Request] Make the THRESHOLD configurable

### ISSUE THREAD

**Issue by lucasfcnunes** [Lootjs/Nuxt-assistant#1]
# Description

Fixed 15 items can be too little to test. Make it configurable.

https://github.com/Lootjs/Nuxt-assistant/blob/4c11af7e2e9b55543d32362013054ed88e624896/nuxt-assistant-panel.js#L365

https://github.com/Lootjs/Nuxt-assistant/blob/4c11af7e2e9b55543d32362013054ed88e624896/nuxt-assistant-panel.js#L381

**Comment by Lootjs** [comment]
Hi! Thanks for reaching out! Do you think this implementation fits your request?

![image](https://github.com/user-attachments/assets/e5306b9a-449e-4006-8a3a-32865fc0aa3b)

![image](https://github.com/user-attachments/assets/01b4b8a5-0241-42b2-a4a4-12f10c8cbf65)

and by default, threshold now is 20

**Comment by lucasfcnunes** [comment]
> Hi! Thanks for reaching out! Do you think this implementation fits your request?

Yes! Thanks for your rapid response!

**Comment by Lootjs** [comment]
Thank you for this idea! i'll publish the new version within 2-3 hours

**Comment by Lootjs** [comment]
Added in 1.20

**Comment by lucasfcnunes** [comment]
@Lootjs, seems that the code here wasn't updated with this feature. Is this right?

**Comment by Lootjs** [comment]
@lucasfcnunes not yet. why?

**Comment by lucasfcnunes** [comment]
> @lucasfcnunes not yet. why?

@Lootjs, you just reopened this issue so it's all good. :)

**Comment by Lootjs** [comment]
@lucasfcnunes here you go https://github.com/Lootjs/Nuxt-assistant/commit/ba16054a88f00d829f46c363b757226f6ad9be34 :))

**Comment by lucasfcnunes** [comment]
> @lucasfcnunes here you go [ba16054](https://github.com/Lootjs/Nuxt-assistant/commit/ba16054a88f00d829f46c363b757226f6ad9be34) :))

Thanks!
